// packages/core/src/constants/abilityMap.ts

export const abilityMap = new Map<number, string>([
    [0, "NONE"],
    [1, "STENCH"],
    [2, "DRIZZLE"],
    [3, "SPEED_BOOST"],
    [4, "BATTLE_ARMOR"],
    [5, "STURDY"],
    [6, "DAMP"],
    [7, "LIMBER"],
    [8, "SAND_VEIL"],
    [9, "STATIC"],
    [10, "VOLT_ABSORB"],
    [11, "WATER_ABSORB"],
    [12, "OBLIVIOUS"],
    [13, "CLOUD_NINE"],
    [14, "COMPOUND_EYES"],
    [15, "INSOMNIA"],
    [16, "COLOR_CHANGE"],
    [17, "IMMUNITY"],
    [18, "FLASH_FIRE"],
    [19, "SHIELD_DUST"],
    [20, "OWN_TEMPO"],
    [21, "SUCTION_CUPS"],
    [22, "INTIMIDATE"],
    [23, "SHADOW_TAG"],
    [24, "ROUGH_SKIN"],
    [25, "WONDER_GUARD"],
    [26, "LEVITATE"],
    [27, "EFFECT_SPORE"],
    [28, "SYNCHRONIZE"],
    [29, "CLEAR_BODY"],
    [30, "NATURAL_CURE"],
    [31, "LIGHTNING_ROD"],
    [32, "SERENE_GRACE"],
    [33, "SWIFT_SWIM"],
    [34, "CHLOROPHYLL"],
    [35, "ILLUMINATE"],
    [36, "TRACE"],
    [37, "HUGE_POWER"],
    [38, "POISON_POINT"],
    [39, "INNER_FOCUS"],
    [40, "MAGMA_ARMOR"],
    [41, "WATER_VEIL"],
    [42, "MAGNET_PULL"],
    [43, "SOUNDPROOF"],
    [44, "RAIN_DISH"],
    [45, "SAND_STREAM"],
    [46, "PRESSURE"],
    [47, "THICK_FAT"],
    [48, "EARLY_BIRD"],
    [49, "FLAME_BODY"],
    [50, "RUN_AWAY"],
    [51, "KEEN_EYE"],
    [52, "HYPER_CUTTER"],
    [53, "PICKUP"],
    [54, "TRUANT"],
    [55, "HUSTLE"],
    [56, "CUTE_CHARM"],
    [57, "PLUS"],
    [58, "MINUS"],
    [59, "FORECAST"],
    [60, "STICKY_HOLD"],
    [61, "SHED_SKIN"],
    [62, "GUTS"],
    [63, "MARVEL_SCALE"],
    [64, "LIQUID_OOZE"],
    [65, "OVERGROW"],
    [66, "BLAZE"],
    [67, "TORRENT"],
    [68, "SWARM"],
    [69, "ROCK_HEAD"],
    [70, "DROUGHT"],
    [71, "ARENA_TRAP"],
    [72, "VITAL_SPIRIT"],
    [73, "WHITE_SMOKE"],
    [74, "PURE_POWER"],
    [75, "SHELL_ARMOR"],
    [76, "CACOPHONY"],
    [77, "AIR_LOCK"]
]);

/**
 * Gets the ability name from the ability ID.
 * @param abilityId - The ability ID.
 * @returns The ability name or undefined if not found.
 */
export function getAbilityName(abilityId: number): string | undefined {
    return abilityMap.get(abilityId);
}
